# bbox
# Autogenerated from man page /usr/share/man/man1/bbox.1.gz
complete -c bbox -s h -l help -d 'Show summary of options'
complete -c bbox -s V -d 'Show version of program'
complete -c bbox -s r -d 'resolution of picture in dpi'

