# cjpeg
# Autogenerated from man page /usr/share/man/man1/cjpeg.1.gz
complete -c cjpeg -o icc -d 'Embed ICC color management profile contained in the specified file'
complete -c cjpeg -o memdst -d 'Compress to memory instead of a file'
complete -c cjpeg -o report -d 'Report compression progress'
complete -c cjpeg -o strict -d 'Treat all warnings as fatal'
complete -c cjpeg -o version -d 'Print version information and exit'

