# clazy
# Autogenerated from man page /usr/share/man/man1/clazy.1.gz
complete -c clazy -l help -d 'Print help message and exit'
complete -c clazy -l version -d 'Print version information and exit'
complete -c clazy -l list -d 'Print a list of all available checkers, arranged by level'
complete -c clazy -l explain -d 'Print explanations for all checkers'
complete -c clazy -l qt4compat -d 'This option runs clazy in Qt4 compatibility mode'

