# compile_et
# Autogenerated from man page /home/lnhutnam/anaconda3/share/man/man1/compile_et.1
complete -c compile_et -l textdomain -d 'option, error messages will be looked up in the specified domain with gettext '
complete -c compile_et -l localedir -d 'option, the text domain will be bound to the specified locale directory with …'

