# ctanbib
# Autogenerated from man page /usr/share/man/man1/ctanbib.1.gz
complete -c ctanbib -s c -l ctan -d 'use @ctan type instead of @manual'
complete -c ctanbib -s C -l CTAN -d 'like --ctan option, but use original url instead of CTAN path'
complete -c ctanbib -s h -l help -d 'print the help message'
complete -c ctanbib -s v -l version -d 'print the version info.  EXAMPLES'

