# djpeg
# Autogenerated from man page /usr/share/man/man1/djpeg.1.gz
complete -c djpeg -o icc -d 'Extract ICC color management profile to the specified file'
complete -c djpeg -o maxscans -d 'Abort if the JPEG image contains more than  N scans'
complete -c djpeg -o memsrc -d 'Load input file into memory before decompressing'
complete -c djpeg -o report -d 'Report decompression progress'
complete -c djpeg -o skip -d 'Decompress all rows of the JPEG image except those between Y0 and Y1 (inclusi…'
complete -c djpeg -o crop -d 'Decompress only a rectangular subregion of the image, starting at point X,Y w…'
complete -c djpeg -o strict -d 'Treat all warnings as fatal'
complete -c djpeg -o version -d 'Print version information and exit.  EXAMPLES'

