# docker-context-ls
# Autogenerated from man page /usr/share/man/man1/docker-context-ls.1.gz
complete -c docker-context-ls -l format -d '	Format output using a custom template: Refer to https://docs. docker'
complete -c docker-context-ls -s h -l help -d '	help for ls'
complete -c docker-context-ls -s q -l quiet -d '	Only show context names SEE ALSO'

