# docker-stack-ls
# Autogenerated from man page /usr/share/man/man1/docker-stack-ls.1.gz
complete -c docker-stack-ls -l format -d '	Format output using a custom template: Refer to https://docs. docker'
complete -c docker-stack-ls -s h -l help -d '	help for ls SEE ALSO'

