# docker-container-attach
# Autogenerated from man page /usr/share/man/man1/docker-container-attach.1.gz
complete -c docker-container-attach -l detach-keys -d 'the key is either a letter [a-Z], or the ctrl-value, where value is one of th…'
complete -c docker-container-attach -s h -l help -d '	help for attach'
complete -c docker-container-attach -l no-stdin -d '	Do not attach STDIN'
complete -c docker-container-attach -l sig-proxy -d '	Proxy all received signals to the process SEE ALSO'

