# docker-volume-update
# Autogenerated from man page /usr/share/man/man1/docker-volume-update.1.gz
complete -c docker-volume-update -l availability -d '	Cluster Volume availability ("active", "pause", "drain")'
complete -c docker-volume-update -s h -l help -d '	help for update SEE ALSO'

