# docker-node-inspect
# Autogenerated from man page /usr/share/man/man1/docker-node-inspect.1.gz
complete -c docker-node-inspect -s f -l format -d '	Format output using a custom template: Refer to https://docs. docker'
complete -c docker-node-inspect -s h -l help -d '	help for inspect'
complete -c docker-node-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO'

