# docker-container-stop
# Autogenerated from man page /usr/share/man/man1/docker-container-stop.1.gz
complete -c docker-container-stop -s h -l help -d '	help for stop'
complete -c docker-container-stop -s s -l signal -d '	Signal to send to the container'
complete -c docker-container-stop -s t -l time -d '	Seconds to wait before killing the container SEE ALSO'

