# docker-context-create
# Autogenerated from man page /usr/share/man/man1/docker-context-create.1.gz
complete -c docker-context-create -l description -d '	Description of the context'
complete -c docker-context-create -l docker -d '	set the docker endpoint'
complete -c docker-context-create -l from -d '	create context from a named context'
complete -c docker-context-create -s h -l help -d '	help for create SEE ALSO'

