# dosepsbin
# Autogenerated from man page /usr/share/man/man1/dosepsbin.1.gz
complete -c dosepsbin -l eps-file -d 'The \\s-1PS\\s0 section is written to <file>'
complete -c dosepsbin -l wmf-file -d 'The \\s-1WMF\\s0 section is written to <file> if present'
complete -c dosepsbin -l tiff-file -d 'The \\s-1TIFF\\s0 section is written to <file> if present'
complete -c dosepsbin -l inputfile -d 'The input file can also be given directly on the command line'
complete -c dosepsbin -l verbose -d 'Verbose messages'
complete -c dosepsbin -l quiet -d 'No messages are printed except for errors and warnings'
complete -c dosepsbin -l help -d 'Display help screen'
complete -c dosepsbin -l man -d 'Prints manual page'

