# dvidvi
# Autogenerated from man page /usr/share/man/man1/dvidvi.1.gz
complete -c dvidvi -s f
complete -c dvidvi -s l
complete -c dvidvi -s n -d 'selected, independently of the number of pages actually contained in a sheet'
complete -c dvidvi -s i
complete -c dvidvi -s x
complete -c dvidvi -s q -d 'messages of how the work is being done'
complete -c dvidvi -s r
complete -c dvidvi -s m -d 'page number are defaulted'

