# gccmakedep
# Autogenerated from man page /usr/share/man/man1/gccmakedep.1.gz
complete -c gccmakedep -s a -d 'Append the dependencies to the file instead of replacing existing dependencies'
complete -c gccmakedep -s f -d Filename
complete -c gccmakedep -s s -d 'Starting string delimiter'
complete -c gccmakedep -s D -d and
complete -c gccmakedep -s U -d 'options to define and undefine symbols and'
complete -c gccmakedep -s I -d 'to set the include path'
complete -c gccmakedep -o f- -d 'sends the output to standard output instead of modifying an existing file'

