# gh-auth-token
# Autogenerated from man page /usr/share/man/man1/gh-auth-token.1.gz
complete -c gh-auth-token -s h -l hostname -d 'The hostname of the GitHub instance authenticated with'
complete -c gh-auth-token -l secure-storage -d 'Search only secure credential store for authentication token SEE ALSO'

