# gh-auth-refresh
# Autogenerated from man page /usr/share/man/man1/gh-auth-refresh.1.gz
complete -c gh-auth-refresh -s h -l hostname -d 'The GitHub host to use for authentication'
complete -c gh-auth-refresh -s s -l scopes -d 'Additional authentication scopes for gh to have'
complete -c gh-auth-refresh -l secure-storage -d 'Save authentication credentials in secure credential store EXAMPLE $ gh auth …'

