# gifcolor
# Autogenerated from man page /home/lnhutnam/anaconda3/share/man/man1/gifcolor.1
complete -c gifcolor -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gifcolor -s b -d 'Set the image\\*(Aqs backround color to a given numeric index'
complete -c gifcolor -s h -d 'Print one line of command line help, similar to Usage above'

