# jcmd-openjdk11
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk11.1.gz
complete -c jcmd-openjdk11 -s f -d 'Reads commands from the specified file'
complete -c jcmd-openjdk11 -o 'h
.br
-help' -d 'Prints a help message'
complete -c jcmd-openjdk11 -s l -d 'Prints the list of running Java processes identifiers with the main class and…'
complete -c jcmd-openjdk11 -s h -d or
complete -c jcmd-openjdk11 -o help -d 'option prints the tool\'s help message'

