# jdb-openjdk11
# Autogenerated from man page /usr/share/man/man1/jdb-openjdk11.1.gz
complete -c jdb-openjdk11 -o help -d 'br Displays a help message'
complete -c jdb-openjdk11 -o sourcepath -d 'br Uses the specified path to search for source files in the specified path'
complete -c jdb-openjdk11 -o attach -d 'br Attaches the debugger to a running JVM with the default connection mechani…'
complete -c jdb-openjdk11 -o listen -d 'br Waits for a running JVM to connect to the specified address with a standar…'
complete -c jdb-openjdk11 -o launch -d 'br Starts the debugged application immediately upon startup of JDB'
complete -c jdb-openjdk11 -o listconnectors -d 'br List the connectors available in this JVM'
complete -c jdb-openjdk11 -o connect -d 'br Connects to the target JVM with the named connector and listed argument va…'
complete -c jdb-openjdk11 -o dbgtrace -d 'br Prints information for debugging the \\f3jdb command'
complete -c jdb-openjdk11 -o tclient -d 'br Runs the application in the Java HotSpot VM client'
complete -c jdb-openjdk11 -o tserver -d 'br Runs the application in the Java HotSpot VM server'
complete -c jdb-openjdk11 -o Joption
complete -c jdb-openjdk11 -s v -o 'verbose[:class'
complete -c jdb-openjdk11 -o Dname
complete -c jdb-openjdk11 -o classpath
complete -c jdb-openjdk11 -o Xoption

