# jinfo-openjdk11
# Autogenerated from man page /usr/share/man/man1/jinfo-openjdk11.1.gz
complete -c jinfo-openjdk11 -o flag -d 'br Prints the name and value of the specified command-line flag'
complete -c jinfo-openjdk11 -o ']name' -d 'br enables or disables the specified Boolean command-line flag'
complete -c jinfo-openjdk11 -o flags -d 'br Prints command-line flags passed to the JVM'
complete -c jinfo-openjdk11 -o sysprops -d 'br Prints Java system properties as name-value pairs'
complete -c jinfo-openjdk11 -s h -d 'br Prints a help message'
complete -c jinfo-openjdk11 -o help

