# jpegtran
# Autogenerated from man page /usr/share/man/man1/jpegtran.1.gz
complete -c jpegtran -o icc -d 'Embed ICC color management profile contained in the specified file'
complete -c jpegtran -o maxscans -d 'Abort if the input image contains more than  N scans'
complete -c jpegtran -o report -d 'Report transformation progress'
complete -c jpegtran -o strict -d 'Treat all warnings as fatal'
complete -c jpegtran -o version -d 'Print version information and exit.  EXAMPLES'

