# jstatd-openjdk11
# Autogenerated from man page /usr/share/man/man1/jstatd-openjdk11.1.gz
complete -c jstatd-openjdk11 -o nr -d 'br Does not attempt to create an internal RMI registry within the \\f3jstatd p…'
complete -c jstatd-openjdk11 -s p -d 'br The port number where the RMI registry is expected to be found, or when no…'
complete -c jstatd-openjdk11 -s n -d 'br Name to which the remote RMI object is bound in the RMI registry'
complete -c jstatd-openjdk11 -o Joption

