# kpsetool
# Autogenerated from man page /usr/share/man/man1/kpsetool.1.gz
complete -c kpsetool -s m -d 'set Metafont mode'
complete -c kpsetool -s n -d 'pretend to be progname to kpathsea'
complete -c kpsetool -s p -d 'act like kpsepath(1)'
complete -c kpsetool -s v -d 'act like kpsexpand(1)'

