# llmk
# Autogenerated from man page /usr/share/man/man1/llmk.1.gz
complete -c llmk -s c -l clean -d 'Remove the temporary files such as *. aux and *. log'
complete -c llmk -s C -l clobber -d 'Remove all generated files including final PDFs'
complete -c llmk -o dCAT -l debug -d 'Activate debug output restricted to CAT'
complete -c llmk -s D -d 'Activate all debug output (equal to "--debug=all")'
complete -c llmk -s h -l help -d 'Print this help message'
complete -c llmk -s n -l dry-run -d 'Show what would have been executed'
complete -c llmk -s q -l quiet -d 'Suppress warnings and most error messages'
complete -c llmk -s s -l silent -d 'Silence messages from called programs'
complete -c llmk -s v -l verbose -d 'Print additional information (e. g. , running commands)'

