# luafindfont
# Autogenerated from man page /usr/share/man/man1/luafindfont.1.gz
complete -c luafindfont -s h -l help -d 'obvious .  :-)'
complete -c luafindfont -s o -l otfinfo -d 'Use the program otfinfo for the font with the given number'
complete -c luafindfont -s i -l info -d 'List the given fontstyles (regular, bold, italic, bolditalic) for the font wi…'
complete -c luafindfont -s v -l verbose -d 'Give more informations, by now only -v works'
complete -c luafindfont -s m -l max_string -d 'The maximum of the stringlength of the full path of fonts'
complete -c luafindfont -s n -l nosymbolicnames -d 'The fontlist contains only fontfile and fontpath'

