# lz4
# Autogenerated from man page /usr/share/man/man1/lz4.1.gz
complete -c lz4 -o BX -d 'Generate block checksums (default:disabled) '
complete -c lz4 -l no-crc -d 'Disable both frame and block checksums '

