# lz4cat
# Autogenerated from man page /usr/share/man/man1/lz4cat.1.gz
complete -c lz4cat -o BX -d 'Generate block checksums (default:disabled) '
complete -c lz4cat -l no-crc -d 'Disable both frame and block checksums '

