# lz4c
# Autogenerated from man page /usr/share/man/man1/lz4c.1.gz
complete -c lz4c -o BX -d 'Generate block checksums (default:disabled) '
complete -c lz4c -l no-crc -d 'Disable both frame and block checksums '

