# lzcat
# Autogenerated from man page /usr/share/man/man1/lzcat.1.gz
complete -c lzcat -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c lzcat -l arm64

