# lzma
# Autogenerated from man page /usr/share/man/man1/lzma.1.gz
complete -c lzma -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c lzma -l arm64

