# makedepend
# Autogenerated from man page /usr/share/man/man1/makedepend.1.gz
complete -c makedepend -o Dname -o Dname -d 'Define.  This places a definition for  name in  makedepend\'s symbol table'
complete -c makedepend -o Iincludedir -d 'Include directory'
complete -c makedepend -o Yincludedir -d 'Replace all of the standard include directories with the single specified inc…'
complete -c makedepend -s a -d 'Append the dependencies to the end of the file instead of replacing them'
complete -c makedepend -o fmakefile -d Filename
complete -c makedepend -o include -d 'Process file as input, and include all the resulting output before processing…'
complete -c makedepend -o oobjsuffix -d 'Object file suffix'
complete -c makedepend -o pobjprefix -d 'Object file prefix.  The prefix is prepended to the name of the object file'
complete -c makedepend -o sstring -d 'Starting string delimiter'
complete -c makedepend -o wwidth -d 'Line width'
complete -c makedepend -s v -d 'Verbose operation'
complete -c makedepend -s m -d 'Warn about multiple inclusion'
complete -c makedepend -s f -d 'option.  It first searches the makefile for the line'
complete -c makedepend -s s -d 'option, as a delimiter for the dependency output'
complete -c makedepend -o 'o.b' -d 'or ``:obj\'\' with'
complete -c makedepend -o o:obj -d 'and so forth'
complete -c makedepend -s I -d and
complete -c makedepend -s D -d 'options; and that most files in a single directory will include largely the s…'

