# makeconv
# Autogenerated from man page /home/lnhutnam/anaconda3/share/man/man1/makeconv.1
complete -c makeconv -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c makeconv -s c -l copyright -d 'Include a copyright notice in the binary data'
complete -c makeconv -s v -l verbose -d 'Display extra informative messages during execution'
complete -c makeconv -s d -l destdir -d 'Set the destination directory to destination '

