# mkoctfile
# Autogenerated from man page /usr/share/man/man1/mkoctfile.1.gz
complete -c mkoctfile -s h -s '?' -l help -d 'Print help message'
complete -c mkoctfile -o Idir -d 'Add include directory dir to compile commands'
complete -c mkoctfile -o idirafterdir -d 'Add include directory to second include search path after \'-I\''
complete -c mkoctfile -o Ddef -d 'Add definition def to compiler command'
complete -c mkoctfile -o llib -d 'Add library lib to link command'
complete -c mkoctfile -o Ldir -d 'Add library directory dir to link command'
complete -c mkoctfile -o Rdir -d 'Pass -Rdir to link command'
complete -c mkoctfile -s g -d 'Enable debugging option for all compilers'
complete -c mkoctfile -o pthread -d 'Add -pthread to link command'
complete -c mkoctfile -s W -d 'Pass flags to the compiler such as -Wa,OPTION'
complete -c mkoctfile -o Wl -d 'Pass flags to the linker such as -Wl,-rpath='
complete -c mkoctfile -s M -l depend -d 'Generate dependency files (. d) for C and C++ source files'
complete -c mkoctfile -s c -d 'Compile but do not link'
complete -c mkoctfile -l link-stand-alone -d 'Link a stand-alone executable file'
complete -c mkoctfile -s s -l strip -d 'Strip the output file'
complete -c mkoctfile -l mex -d 'Create a MEX file.   Set the default output extension to . mex'
complete -c mkoctfile -s o -l output -d 'Output filename.   Default extension is . oct (or '
complete -c mkoctfile -s p -l print -d 'Print configuration variable VAR.   There are three categories of variables:'
complete -c mkoctfile -s v -l verbose -d 'Echo commands as they are executed'
complete -c mkoctfile -l prefix -l exec-prefix -d configured

