# nmbug
# Autogenerated from man page /usr/share/man/man1/nmbug.1.gz
complete -c nmbug -s h -l help -d 'show help message and exit . UNINDENT NDENT 0. 0'
complete -c nmbug -s N -l nmbug -d 'Set defaults for \\%--tag-prefix and \\%--git-dir suitable for the \\%notmuch bu…'
complete -c nmbug -s C -l git-dir -d 'Operate on git repository repo.  See \\%REPOSITORY LOCATION for defaults'
complete -c nmbug -s p -l tag-prefix -d 'Operate only on tags with prefix prefix.  See \\%PREFIX VALUE for defaults'
complete -c nmbug -s v -l version -d 'show notmuch-git\\(aqs version number and exit . UNINDENT NDENT 0. 0'
complete -c nmbug -s l -l log-level -d 'Log verbosity, one of: critical, error, warning, info, debug'
complete -c nmbug -s f -l force -d 'UNINDENT . sp Update the notmuch database from Git'
complete -c nmbug -l format-version -d 'UNINDENT . sp Create an empty notmuch git repository'

