# octave-config
# Autogenerated from man page /usr/share/man/man1/octave-config.1.gz
complete -c octave-config -l m-site-dir -d 'Display the main directory for local, or site-specific, . m script files'
complete -c octave-config -l oct-site-dir -d 'Display the main directory for local, or site-specific, '
complete -c octave-config -s p -l print -d 'Print the default value of the Octave configuration variable VAR'
complete -c octave-config -s v -l version -d 'Display the version number of  octave (1)'
complete -c octave-config -s h -s '?' -l help -d 'Print help message.  AUTHOR John W.  Eaton <jwe@octave. org>'

