# pamphletangler
# Autogenerated from man page /usr/share/man/man1/pamphletangler.1.gz
complete -c pamphletangler -s L -l line -d 'If set, this text will be inserted after jumps of lines, changing the string …'
complete -c pamphletangler -s C -l change -d 'Defaults to \\*(L"{}\\*(R" this is the text that will be replaced with the line…'
complete -c pamphletangler -s '?' -l help -d 'Give this help list'
complete -c pamphletangler -l usage -d 'Give a short usage message'
complete -c pamphletangler -l man -d 'Print manual page'

