# rmic-openjdk11
# Autogenerated from man page /usr/share/man/man1/rmic-openjdk11.1.gz
complete -c rmic-openjdk11 -o bootclasspath -d 'br Overrides the location of bootstrap class files'
complete -c rmic-openjdk11 -o classpath -d 'br Specifies the path the \\f3rmic command uses to look up classes'
complete -c rmic-openjdk11 -s d -d 'br Specifies the root destination directory for the generated class hierarchy'
complete -c rmic-openjdk11 -o extdirs -d 'br Overrides the location of installed extensions'
complete -c rmic-openjdk11 -s g -d 'br Enables the generation of all debugging information, including local varia…'
complete -c rmic-openjdk11 -o idl -d 'br Causes the \\f3rmic command to generate OMG IDL for the classes specified a…'
complete -c rmic-openjdk11 -o iiop -d 'br Causes the \\f3rmic command to generate IIOP stub and tie classes, rather t…'
complete -c rmic-openjdk11 -s J -d 'br Used with any Java command, the \\f3-J option passes the argument that foll…'
complete -c rmic-openjdk11 -o keep -o keepgenerated -d 'br Retains the generated \\f3'
complete -c rmic-openjdk11 -o nowarn -d 'br Turns off warnings.  When the \\f3-nowarn options is used'
complete -c rmic-openjdk11 -o nowrite -d 'br Does not write compiled classes to the file system'
complete -c rmic-openjdk11 -o vcompat -d 'br Generates stub and skeleton classes that are compatible with both the 1'
complete -c rmic-openjdk11 -o verbose -d 'br Causes the compiler and linker to print out messages about what classes ar…'
complete -c rmic-openjdk11 -o 'v1.1' -d 'br Generates stub and skeleton classes for the 1'
complete -c rmic-openjdk11 -o idlFilefromJavaPackage -o idlFile
complete -c rmic-openjdk11 -o 'v1.2'

