# serialver-openjdk11
# Autogenerated from man page /usr/share/man/man1/serialver-openjdk11.1.gz
complete -c serialver-openjdk11 -o classpath -d 'br Sets the search path for application classes and resources'
complete -c serialver-openjdk11 -o show -d 'br Displays a simple user interface'
complete -c serialver-openjdk11 -o Joption
complete -c serialver-openjdk11 -o 'J-Djava.security.manager' -d 'When necessary, a security policy can be specified with the following option:'
complete -c serialver-openjdk11 -o 'J-Djava.security.policy' -d 'SEE ALSO    '

