# spix
# Autogenerated from man page /usr/share/man/man1/spix.1.gz
complete -c spix -s n -l dry-run -d 'Print the commands that would be executed, but do not execute them'
complete -c spix -s h -l help -d 'Print help, and exit'
complete -c spix -l version -d 'Print version, and exit.  EXAMPLES Let foo. tex be the following file'

