# t1lint
# Autogenerated from man page /usr/share/man/man1/t1lint.1.gz
complete -c t1lint -s q -l quiet -d 'Do not generate any error messages.   The only output will be the exit status'
complete -c t1lint -s h -l help -d 'Print usage information and exit.  \' . Sp'
complete -c t1lint -s v -l version -d 'Print the version number and some short non-warranty information and exit'

