# thumbpdf
# Autogenerated from man page /usr/share/man/man1/thumbpdf.1.gz
complete -c thumbpdf -l help -d 'print usage'
complete -c thumbpdf -l resolution -d 'resolution for GhostScript step (default: 9)'
complete -c thumbpdf -l compress -d 'pdfcompresslevel for thumbpdf. pdf (0-9; default: 9)'

