# unlz4
# Autogenerated from man page /usr/share/man/man1/unlz4.1.gz
complete -c unlz4 -o BX -d 'Generate block checksums (default:disabled) '
complete -c unlz4 -l no-crc -d 'Disable both frame and block checksums '

