# unlzma
# Autogenerated from man page /usr/share/man/man1/unlzma.1.gz
complete -c unlzma -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c unlzma -l arm64

