# unxz
# Autogenerated from man page /usr/share/man/man1/unxz.1.gz
complete -c unxz -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c unxz -l arm64

