# unzstd
# Autogenerated from man page /usr/share/man/man1/unzstd.1.gz
complete -c unzstd -s l -l list -d 'Display information related to a zstd compressed file, such as size, ratio, a…'
complete -c unzstd -s n -l no-name -d 'do not store the original filename and timestamps when compressing a file'

