# xine-config
# Autogenerated from man page /usr/share/man/man1/xine-config.1.gz
complete -c xine-config -l version -d '--modversion '
complete -c xine-config -l libs -d 'TQ 8   --cflags . TQ 8   --objcflags Passed on unmodified'
complete -c xine-config -l bindir -d 'TQ 8   --plugindir . TQ 8   --datadir . TQ 8   --scriptdir '
complete -c xine-config -l prefix -d '--define-variable=prefix=PREFIX '
complete -c xine-config -l modversion
complete -c xine-config -l cflags
complete -c xine-config -l objcflags -d 'Passed on unmodified'
complete -c xine-config -l plugindir
complete -c xine-config -l datadir
complete -c xine-config -l scriptdir
complete -c xine-config -l localedir
complete -c xine-config -l variable
complete -c xine-config -l define-variable
complete -c xine-config -l exec-prefix

