# xine-list-1.2
# Autogenerated from man page /usr/share/man/man1/xine-list-1.2.1.gz
complete -c 'xine-list-1.2' -s m -d '--mime-types List the MIME types known to xine-lib'
complete -c 'xine-list-1.2' -s e -d '--extensions List the file types (filename extensions) known to xine-lib'
complete -c 'xine-list-1.2' -s a -d '--all List the MIME types known to xine-lib, along with their filename extens…'
complete -c 'xine-list-1.2' -l mime-types -d 'List the MIME types known to xine-lib.  (This is the default action. )'
complete -c 'xine-list-1.2' -l extensions -d 'List the file types (filename extensions) known to xine-lib'
complete -c 'xine-list-1.2' -l all -d 'List the MIME types known to xine-lib, along with their filename extensions a…'
complete -c 'xine-list-1.2' -s p
complete -c 'xine-list-1.2' -l pretty-print -d 'Add line feeds; print each item on a line of its own'

