# xkbcli-interactive-x11
# Autogenerated from man page /home/lnhutnam/anaconda3/share/man/man1/xkbcli-interactive-x11.1
complete -c xkbcli-interactive-x11 -o '\\-help' -d 'Print help and exit El SEE ALSO xkbcli 1, xkbcli\\-interactive\\-evdev 1, xkbcl…'

