# xkbcli-how-to-type
# Autogenerated from man page /usr/share/man/man1/xkbcli-how-to-type.1.gz
complete -c xkbcli-how-to-type -o '\\-keysym' -d 'Treat the argument as a keysym, not a Unicode codepoint'

