# xkbcli
# Autogenerated from man page /home/lnhutnam/anaconda3/share/man/man1/xkbcli.1
complete -c xkbcli -o '\\-help' -d 'Print help and exit'
complete -c xkbcli -o '\\-version' -d 'Print the version and exit El COMMANDS -tag -width Ds how\\-to\\-type Show how …'

