# xzcat
# Autogenerated from man page /usr/share/man/man1/xzcat.1.gz
complete -c xzcat -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c xzcat -l arm64

