# zstdcat
# Autogenerated from man page /usr/share/man/man1/zstdcat.1.gz
complete -c zstdcat -s l -l list -d 'Display information related to a zstd compressed file, such as size, ratio, a…'
complete -c zstdcat -s n -l no-name -d 'do not store the original filename and timestamps when compressing a file'

